import { esc } from "../utils/dom.js";

export function renderAccountGateHtml() {
  return `<section class="accountGate"><div class="gateMark"><img src="/icons/icon-192.png" alt="" aria-hidden="true"></div><h1>Join LineUp</h1><p>LineUp is account-based so reports, rewards, favorites, and moderation can scale across campuses. You can still appear anonymous publicly.</p><button class="secondaryBtn appleBtn" onclick="showToast('Sign in with Apple will be added for the native app')">Continue with Apple</button><label class="fieldLabel">Email</label><input class="field" id="authEmail" type="email" autocomplete="email" placeholder="you@email.com"><label class="fieldLabel">Password</label><input class="field" id="authPassword" type="password" autocomplete="current-password" placeholder="6+ characters"><label class="fieldLabel">Display name for new accounts</label><input class="field" id="authName" maxlength="32" placeholder="Display name"><div class="sheetActions"><button class="secondaryBtn" onclick="submitEmailAuth('signin')">Sign In</button><button class="submit" onclick="submitEmailAuth('signup')">Create Account</button></div><p class="rewardFine">By continuing, you agree to LineUp’s <button class="linkBtn" onclick="showLegalSheet('privacy')">Privacy</button> and <button class="linkBtn" onclick="showLegalSheet('terms')">Terms</button>. SMS login is intentionally not used.</p></section>`;
}

export function renderSetupGateHtml({ mode, avatarHtml, displayName, favoritesHtml }) {
  return `<section class="accountGate setupGate"><div class="profileMark setupAvatar">${avatarHtml}</div><h1>Set Up LineUp</h1><p>Keep it fast: choose how you appear, pick favorites, and enable the permissions that make live reads smarter.</p><label class="fieldLabel">Profile photo</label><input class="field" type="file" accept="image/*" onchange="handleAvatarFile(this)"><label class="fieldLabel">Display name</label><input class="field" id="setupName" maxlength="32" value="${esc(displayName || "")}" placeholder="Display name"><label class="fieldLabel">Public mode</label><div class="identityToggle"><button class="${mode === "anonymous" ? "on" : ""}" onclick="setInteractionVisibility('anonymous')">Anonymous</button><button class="${mode === "public" ? "on" : ""}" onclick="setInteractionVisibility('public')">Public</button></div><p class="rewardFine">Anonymous Mode shows public posts and reports as “Anonymous User.” LineUp still links activity to your account for moderation and safety.</p><div class="sectionlabel">Favorite bars</div><div class="favSetup">${favoritesHtml}</div><div class="sheetActions"><button class="secondaryBtn" onclick="requestNotifications()">Notifications</button><button class="secondaryBtn" onclick="requestSetupLocation()">Location</button></div><button class="submit" onclick="saveSetup()">Finish Setup</button><p class="rewardFine">Permissions are optional and can be changed later in Preferences.</p></section>`;
}
