import { esc } from "../utils/dom.js";
import { timeAgo } from "../utils/time.js";

export function renderDetailHtml(ctx) {
  const { bar, reports, detailTab, level, signalState, confColor, colors, svg, logo, isFavorite, detailMiniRow, detailPanel, dealBlock, canManageVenue = false, launchDealRequested = false, showLaunchDealRequest = true } = ctx;
  if (!bar) return '<div class="detailtop"><button class="iconbtn" onclick="closeDetail()">Back</button></div><div class="card"><b>Venue unavailable</b><p class="muted intelCopy">This venue could not be loaded. Refresh LineUp and try again.</p></div>';
  const currentLevel = level(bar);
  const signal = signalState(bar);
  const decision = bar.wait > 20 ? "Worth checking before you leave" : bar.lvl === "packed" ? "Go if you want peak energy" : bar.lvl === "busy" ? "Strong option right now" : "Easy option right now";
  const ownerTools = canManageVenue ? `<div class="ownerPreviewStrip"><div><b>Staff preview</b><span>You are viewing the student venue page.</span></div><button class="secondaryBtn" onclick="openAdminForVenue('${bar.id}')">Manage Venue</button></div>` : "";
  const launchRequest = showLaunchDealRequest ? `<button class="cta launchDealRequest ${launchDealRequested?"requested":""}" ${launchDealRequested?"disabled":""} onclick="requestLaunchDeal('${bar.id}')"><span>${launchDealRequested?"Launch deal requested":"Request a launch deal"}</span><small>${launchDealRequested?"Interest saved for this venue":"Send aggregate interest to the venue"}</small></button>` : "";
  return `<div class="detailtop"><button class="iconbtn" onclick="closeDetail()"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.2"><path d="M15 18l-6-6 6-6"/></svg></button><div style="flex:1"></div><button class="iconbtn fav ${isFavorite(bar.id)?"on":""}" onclick="toggleFav('${bar.id}')">${isFavorite(bar.id)?svg.starFull:svg.starEmpty}</button></div><div class="detailtop">${logo(bar)}<div><div class="dtitle">${esc(bar.name)}</div><div class="tag">${esc(bar.tag)}</div><div class="addr">${esc(bar.address)}</div></div></div>${ownerTools}<div class="heroStat"><div class="heroRow"><div><div class="heroCrowd" style="color:${colors[bar.lvl]}">${currentLevel.label}</div><div class="muted">Likely ${currentLevel.range}</div></div><div><div class="heroLine">${bar.wait?bar.wait+" min":"No line"}</div><div class="muted">est. line</div></div></div><div class="barline"><div style="width:${currentLevel.pct}%;background:${colors[bar.lvl]}"></div></div><div class="conf"><span class="dot" style="background:${confColor(signal.tone)}"></span>${esc(signal.label)} · ${esc(signal.detail)}</div></div><div class="detailDecision"><b>${esc(decision)}</b><span>${bar.wait?bar.wait+" min line":"No line"} · ${esc(currentLevel.range)}</span></div>${dealBlock||""}${launchRequest}${detailMiniRow(bar)}<div class="tabs2"><button class="${detailTab==="live"||detailTab==="highlights"?"on":""}" onclick="setDetailTab('live')">Live</button><button class="${detailTab==="stats"?"on":""}" onclick="setDetailTab('stats')">Intel</button><button class="${detailTab==="events"?"on":""}" onclick="setDetailTab('events')">Events</button></div>${detailPanel(bar,reports)}<div class="ctaGrid"><button class="cta" onclick="openMaps(current)"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.2"><path d="M12 21s7-6.1 7-11a7 7 0 0 0-14 0c0 4.9 7 11 7 11z"/><circle cx="12" cy="10" r="2.4"/></svg><span>Directions</span></button><button class="cta" onclick="checkInCurrent()"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.2"><path d="M20 6L9 17l-5-5"/></svg><span>Check in</span><small>Verify nearby</small></button><button class="cta" onclick="openReport()"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg><span>Report</span><small>Update status</small></button></div>`;
}

export function renderDetailMiniRow(bar, { closeText, coverLabel, svg }) {
  if (!bar) return "";
  const cover = coverLabel(bar);
  const items = ['<div class="mini"><span><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 3"/></svg></span><b>Hours</b><small>'+closeText(bar)+'</small></div>'];
  if (cover) items.push('<div class="mini"><span><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"/><line x1="7" y1="7" x2="7.01" y2="7"/></svg></span><b>Cover</b><small>'+cover+'</small></div>');
  items.push('<div class="mini"><span>'+svg.lastcall+'</span><b>Last Call</b><small>'+bar.lastCall+'</small></div>');
  return '<div class="minirow">'+items.join("")+'</div>';
}

export function renderConfidenceBreakdown(bar, { signalState, escSource }) {
  if (!bar) return '<div class="confidenceRows"><div class="confidenceRow"><b>Current read</b><span>Unavailable</span></div></div>';
  const signal = signalState(bar);
  const sourceRows = (bar.sources||[]).slice(0,5).map((source) => {
    const text = String(source).toLowerCase();
    const weight = text.indexOf("owner")>-1 ? "Highest trust" : text.indexOf("venue")>-1||text.indexOf("staff")>-1 ? "Venue confirmed" : text.indexOf("verified")>-1||text.indexOf("scout")>-1 ? "Verified signal" : text.indexOf("report")>-1 ? "Crowd signal" : text.indexOf("historical")>-1||text.indexOf("typical")>-1 ? "Baseline prior" : "Supporting";
    return '<div class="confidenceRow"><b>'+escSource(source)+'</b><span>'+weight+'</span></div>';
  }).join("");
  return `<div class="confidenceRows"><div class="confidenceRow"><b>Current read</b><span>${esc(signal.label)}</span></div><div class="confidenceRow"><b>Freshness</b><span>${esc(signal.detail)}</span></div><div class="confidenceRow"><b>Data mode</b><span>${esc(signal.mode)}</span></div><div class="confidenceRow"><b>Recent inputs</b><span>${bar.confSignals||0} signals</span></div>${sourceRows}</div><p class="rewardFine">LineUp blends staff updates, verified nearby reports, check-ins, app demand, and historical baselines. Higher-trust sources count more, and older signals fade toward a typical read for this time.</p>`;
}

export function renderReportRows(reports, { levels, svg }) {
  const rows = Array.isArray(reports) ? reports : [];
  if (!rows.length) return '<div class="reportrow"><div class="avatar">L</div><div><b>LineUp</b><div class="muted">No live reports yet tonight.</div></div><div class="chev">'+svg.chevRight+'</div></div>';
  function initial(name){var s=String(name||"A").trim();return esc((s[0]||"A").toUpperCase())}
  function reportTime(report){if(report.empty)return"";if(report.seed_time)return report.seed_time;return report.created_at?timeAgo(report.created_at):"just now"}
  function summary(report){var parts=[];if(report.crowd_level&&levels[report.crowd_level])parts.push(levels[report.crowd_level].label+" crowd");if(Number(report.wait_minutes)>0)parts.push(Number(report.wait_minutes)+" min line");else if(report.crowd_level)parts.push("No line");if(report.location_verified)parts.push("verified nearby");return parts.join(" · ")}
  return rows.map(function(report,index){var author=report.author||{},name=author.name||"Anonymous User",fallback=report.empty?"var(--surface)":index===0?"var(--packed)":index===1?"var(--busy)":"var(--slow)",avatar=author.avatar_url?'<img src="'+esc(author.avatar_url)+'" alt="">':initial(name),meta=report.empty?"":[reportTime(report),author.anonymous?"anonymous":(report.location_verified?"verified nearby":"public")].filter(Boolean).join(" · "),text=summary(report)||"Useful venue signal";return '<div class="reportrow"><div class="avatar" style="background:'+fallback+'">'+avatar+'</div><div><b>'+esc(name)+' <span class="muted">'+esc(meta)+'</span></b><div class="muted">'+esc(text)+'</div></div><div class="chev">'+svg.chevRight+'</div></div>'}).join("");
}

export function renderDetailPanel(bar, reports, ctx) {
  if (!bar) return '<div class="card"><b>Venue unavailable</b><p class="muted intelCopy">Live activity is not available for this venue yet.</p></div>';
  const signal = ctx.signalState(bar);
  const reportCount = Array.isArray(reports) ? reports.filter(function(r){return r && !r.empty;}).length : 0;
  const lowData = signal.key==="low" || signal.key==="typical";
  if (ctx.detailTab==="events") return `<div class="card"><b>Tonight at ${esc(bar.name)}</b><p class="muted" style="margin-top:8px">${esc(bar.event||"No posted event yet.")}</p></div>`;
  if (ctx.detailTab==="stats") return `<div class="card"><b>Read summary</b><div class="row"><span>Momentum</span><b>${ctx.cap(bar.momentum.replace("_"," "))}</b></div><div class="row"><span>Read quality</span><b style="color:${ctx.confColor(signal.tone)}">${esc(signal.label)}</b></div><div class="row"><span>Recent inputs</span><b>${bar.confSignals||0}</b></div></div><div class="card"><b>Why this read</b>${ctx.confidenceBreakdown(bar)}</div>`;
  return `<div class="card"><b>Live activity</b><p class="muted" style="margin-top:6px">${esc(signal.label)} · ${esc(signal.detail)}.</p><div class="row" style="margin-top:10px"><span>Est. line wait</span><b>${bar.wait?bar.wait+" min":"No line"}</b></div><div class="row"><span>Recent reports</span><b>${reportCount}</b></div><div class="row"><span>Read quality</span><b style="color:${ctx.confColor(signal.tone)}">${esc(signal.mode)}</b></div>${lowData?'<p class="rewardFine">Low recent data · showing typical pattern.</p>':""}</div><details class="card photoPanel"><summary>Confidence <span class="muted">Why this read</span></summary>${ctx.confidenceBreakdown(bar)}</details><div class="sectionlabel">RECENT REPORTS</div><div class="card">${ctx.renderReportRows(reports)}<button class="field" onclick="loadVenueReports(current.id);showToast('Refreshing live reports')">Refresh reports</button></div>`;
}
