import { createClient } from "@supabase/supabase-js";
import "mapbox-gl/dist/mapbox-gl.css";
import { ASSET_LOGOS, SVG, COLORS, LEVELS, BARS as BAR_SEED } from "./data.js";
import { ACTIVE_STATUS_SELECT, APP_VERSION, MAP_CENTER, REWARD_GOAL, SUPABASE_KEY, SUPABASE_URL, USER_COORDS, deviceSessionEnabled, mapboxToken } from "./config.js";
import { $, $all, esc } from "./utils/dom.js";
import { hour, minutesSince, timeAgo } from "./utils/time.js";
import { createInstallPromptController } from "./services/installPrompt.js";
import { createDeviceSessionService } from "./services/deviceSessionService.js";
import { createLineupApiService } from "./services/lineupApiService.js";
import { createAccountService } from "./services/accountService.js";
import { createRewardService } from "./services/rewardService.js";
import { createReportService } from "./services/reportService.js";
import { createLocationService } from "./services/locationService.js";
import { createVenueService } from "./services/venueService.js";
import { createInitialAppState, cloneVenue } from "./state/appState.js";
import * as cacheState from "./state/cacheState.js";
import { selectAdminVenue, selectArea, selectDetailTab, selectDetailVenue, selectPage, selectProfileView, selectPulseVibe, selectReportLevel } from "./controllers/navigationController.js";
import { createBarDetailController } from "./controllers/barDetailController.js";
import { createMapController } from "./controllers/mapController.js";
import { createOwnerController } from "./controllers/ownerController.js";
import { createReportController } from "./controllers/reportController.js";
import { createVenueStaffController } from "./controllers/venueStaffController.js";
import { renderAccountGateHtml, renderSetupGateHtml } from "./ui/renderShell.js";
import { areaPulseCopy as dashboardPulseCopy, renderBarCard, renderLiveDashboard } from "./ui/renderDashboard.js";
import { renderConfidenceBreakdown as renderDetailConfidenceBreakdown, renderDetailHtml, renderDetailMiniRow, renderDetailPanel, renderReportRows as renderDetailReportRows } from "./ui/renderBarDetail.js";
import { renderReportSheetHtml } from "./ui/renderReportSheet.js";
import { legalCopy as profileLegalCopy, renderLegalSheetHtml, renderProfilePageHtml, renderRewardsHtml } from "./ui/renderProfile.js";
import { circlePolygon, createVenueMarker, fallbackMapHtml, mapShellHtml, mapUnavailableHtml } from "./ui/renderMap.js";
import { noVenueRoleHtml, renderVenueControlsForBar } from "./ui/renderVenueControls.js";
import { loadingOwnerDashboardHtml, renderOwnerDashboardHtml, renderOwnerVenueDetailHtml } from "./ui/renderOwnerDashboard.js";

var installPrompt=createInstallPromptController();
installPrompt.registerInstallEvents();
var handleInstallPrimary=installPrompt.handleInstallPrimary,handleInstallSecondary=installPrompt.handleInstallSecondary;
function initialPage(){var p=new URLSearchParams(location.search).get("page"),allowed=["livePage","mapPage","highlightsPage","profilePage","statsPage"];return allowed.indexOf(p)>-1?p:"livePage"}
cacheState.clearLegacyVenueOverrides();
var appState=createInitialAppState({bars:BAR_SEED,activePage:initialPage(),area:cacheState.getArea()});
var BARS=appState.backend.venues,REMOTE_REPORTS=appState.backend.reportsByVenue;
var MAPBOX_TOKEN=mapboxToken(),rewardSummary=cacheState.getRewardSummary(),authState=cacheState.getAuthState(),authAccessToken=appState.auth.accessToken,accountPermissions=cacheState.getAccountPermissions(),mapboxReady=appState.map.mapboxReady,mapboxgl=appState.map.mapboxgl,mapInstance=appState.map.mapInstance,ownerMap=appState.map.ownerMap,mapMarkers=appState.map.markers,supabaseClient=null,supabaseReady=appState.backend.supabaseReady,selectedReportLevel=appState.ui.selectedReportLevel,adminVenueId=appState.ui.adminVenueId,ownerData=appState.backend.ownerData,lastPosition=appState.location.lastPosition,presenceState=cacheState.getPresenceState(),profileSummary=cacheState.getProfileSummary(),accountPrefs=cacheState.getAccountPrefs(),activityLog=cacheState.getActivityLog(),locationBusy=appState.ui.locationBusy,lastPresenceAt=appState.location.lastPresenceAt,liveLocationWatchId=appState.location.liveLocationWatchId,liveLocationLastSent=appState.location.liveLocationLastSent,liveLocationSending=appState.ui.liveLocationSending,favs=cacheState.getFavorites(),area=appState.ui.area,active=appState.ui.activePage,profileView=appState.ui.profileView,detailTab=appState.ui.detailTab,intelMode=appState.ui.intelMode,pulseVibe=appState.ui.pulseVibe,current=appState.ui.currentVenue,toastTimer=appState.ui.toastTimer,mapPan=appState.ui.mapPan;
if(area==="U")area=selectArea(appState,"main_gate",cacheState);if(area==="P")area=selectArea(appState,"fourth_downtown",cacheState);
var FALLBACK_BARS=appState.backend.fallbackVenues;
var deviceSessionService=createDeviceSessionService({supabaseUrl:SUPABASE_URL,supabaseKey:SUPABASE_KEY,enabled:deviceSessionEnabled(),getHeaders:rewardHeaders});
var lineupApi=createLineupApiService({supabaseUrl:SUPABASE_URL,supabaseKey:SUPABASE_KEY,getHeaders:rewardHeaders,withDeviceProof:function(body){return deviceSessionService.withDeviceProof(body)}});
var accountService=createAccountService({deviceFunctionRequest:lineupApi.deviceFunctionRequest});
var rewardService=createRewardService({deviceFunctionRequest:lineupApi.deviceFunctionRequest});
var reportService=createReportService({publicFunctionRequest:lineupApi.publicFunctionRequest,rawDevicePost:lineupApi.rawDevicePost,supabaseUrl:SUPABASE_URL,getHeaders:rewardHeaders});
var locationService=createLocationService({deviceFunctionRequest:lineupApi.deviceFunctionRequest});
var venueService=createVenueService({activeStatusSelect:ACTIVE_STATUS_SELECT});
var barDetailController,reportController,ownerController,venueStaffController,mapController;
function saveFavs(){cacheState.setFavorites(favs)}
function initSupabase(){if(!SUPABASE_URL||!SUPABASE_KEY)return;supabaseClient=createClient(SUPABASE_URL,SUPABASE_KEY);loadAuthState();loadSupabaseStatus();loadDeviceProfile();loadRewardSummary();subscribeSupabaseStatus();subscribeSupabaseReports()}
function loadSupabaseStatus(){if(!supabaseClient)return Promise.resolve(BARS);return venueService.loadActiveStatus(supabaseClient).then(function(res){if(res.error)throw res.error;var rows=res.data||[];if(rows.length)BARS=rows.map(remoteVenue);supabaseReady=true;appState.backend.venues=BARS;appState.backend.supabaseReady=true;renderAll();if(current){current=BARS.find(b=>b.id===current.id)||current;appState.ui.currentVenue=current;renderDetail()}return BARS}).catch(function(){if(!supabaseReady){BARS=FALLBACK_BARS.map(cloneVenue);appState.backend.venues=BARS;renderAll()}showToast("Using local LineUp data");return BARS})}
function subscribeSupabaseStatus(){if(!supabaseClient)return;venueService.subscribeStatus(supabaseClient,function(){loadSupabaseStatus()})}
function subscribeSupabaseReports(){if(!supabaseClient)return;venueService.subscribeReports(supabaseClient,function(payload){var id=payload.new&&payload.new.venue_id;if(id)loadVenueReports(id)})}
function remoteVenue(row){var base=FALLBACK_BARS.find(v=>v.id===row.id)||{},logo=row.logo_key||base.logo||(row.name||"").slice(0,2).toUpperCase(),score=row.confidence_score==null?null:Number(row.confidence_score),signals=row.confidence_signal_count==null?0:Number(row.confidence_signal_count),sources=row.sources&&row.sources.length?row.sources:(base.sources||["Supabase venue data","Historical baseline"]);return Object.assign({},base,{id:row.id,area:row.area==="university"?"main_gate":row.area==="main_gate"?"main_gate":"fourth_downtown",status:row.status||"active",deprecated:!!row.deprecated,name:row.name||base.name||row.id,tag:row.tag||base.tag||"Venue",address:row.address||base.address||"",mapQuery:row.map_query||base.mapQuery||((row.name||row.id)+" "+(row.address||"Tucson AZ")),coords:{lat:Number(row.lat)||base.coords&&base.coords.lat||32.2292,lng:Number(row.lng)||base.coords&&base.coords.lng||-110.9612},scenes:row.scenes&&row.scenes.length?row.scenes:(base.scenes||["friends"]),logo:logo,open:row.open_hour==null?(base.open||20):row.open_hour,close:row.close_hour==null?(base.close||2):row.close_hour,lastCall:row.last_call||base.lastCall||"1:45 AM",lineLeap:row.line_leap_url||base.lineLeap,event:row.event||base.event||"Live tonight",lvl:LEVELS[row.crowd_level]?row.crowd_level:(base.lvl||"slow"),wait:row.wait_minutes==null?(base.wait||0):row.wait_minutes,conf:row.confidence||base.conf||"low",confScore:score,confSignals:signals,momentum:row.momentum||base.momentum||"steady",cover:row.cover_amount||base.cover||"$0",coverActive:!!row.cover_active,sources:sources,fresh:minutesSince(row.fresh_at||row.status_updated_at),backend:true})}
function applyRemoteVenue(row){var next=remoteVenue(row),i=BARS.findIndex(v=>v.id===next.id);if(i>=0)BARS[i]=next;else BARS.push(next)}
function reportPayload(b,patch,note,photo){return{crowd_level:patch.lvl,wait_minutes:patch.wait,cover_amount:patch.cover,cover_active:patch.coverActive,note:note||null,photo_signal:!!photo,report_context:{app_version:APP_VERSION,ui_source:"report_sheet"}}}
function syncReportWithoutLocation(b,patch,note,photo){return reportService.syncReportWithoutLocation(Object.assign({action:"report",venue_id:b.id,interaction_visibility:interactionVisibility(),display_name:accountPrefs.display_name||"",avatar_url:accountPrefs.avatar_url||""},reportPayload(b,patch,note,photo)))}
function syncReportToSupabase(b,patch,note,photo){if(!SUPABASE_URL||!SUPABASE_KEY||!authState)return Promise.resolve({verified:false,offline:true});return getFreshPosition(90000).then(function(pos){return sendLocationIngest("report",b.id,pos,reportPayload(b,patch,note,photo))}).catch(function(){return syncReportWithoutLocation(b,patch,note,photo).catch(function(){return{verified:false,offline:true}})})}
function loadVenueReports(venueId){if(!SUPABASE_URL||!SUPABASE_KEY||!venueId)return Promise.resolve(reportRows(venueId));return reportService.loadVenueReports(venueId).then(function(data){REMOTE_REPORTS[venueId]=data.reports||[];if(current&&current.id===venueId&&$("#detail").classList.contains("open"))renderDetail();return REMOTE_REPORTS[venueId]}).catch(function(){return reportRows(venueId)})}
function getDeviceId(){return deviceSessionService.getDeviceId()}
function getSessionId(){return deviceSessionService.getSessionId()}
function applyPermissions(perms){accountPermissions=Object.assign({owner:false,roles:[],venues:[]},perms||{});cacheState.setAccountPermissions(accountPermissions);renderRoleTabs()}
function isOwnerAccount(){return !!(accountPermissions&&accountPermissions.owner)}
function assignedVenues(){return (accountPermissions&&accountPermissions.venues||[]).filter(function(v){return v&&v.id})}
function canUseVenueControls(){return isOwnerAccount()||assignedVenues().length>0}
function canAdminVenue(id){if(isOwnerAccount())return true;return assignedVenues().some(function(v){return v.id===id})}
function defaultControlVenueId(){var venues=assignedVenues();return isOwnerAccount()?activeBars()[0]&&activeBars()[0].id:venues[0]&&venues[0].id}
function roleTabIcon(venue){var key=venue&&venue.logo_key,img=key&&ASSET_LOGOS[key];return img?'<img src="'+esc(img)+'" alt="" class="navVenueLogo">':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20V9l8-5 8 5v11"/><path d="M9 20v-6h6v6"/><path d="M8 10h.01M16 10h.01"/></svg>'}
function bindNavButtons(){$all(".navbtn").forEach(function(b){b.onclick=function(){setPage(b.dataset.page)}})}
function renderRoleTabs(){var nav=$(".navinner");if(!nav)return;var existing=$("#roleNavButton");if(existing)existing.remove();nav.classList.toggle("has-role",canUseVenueControls());if(!canUseVenueControls())return;var venue=assignedVenues()[0],label=isOwnerAccount()?"Control":(venue&&venue.name?venue.name.split(" ")[0]:"Venue"),icon=isOwnerAccount()?SVG.ownerOps:roleTabIcon(venue),btn=document.createElement("button");btn.className="navbtn roleNav";btn.id="roleNavButton";btn.dataset.page="statsPage";btn.innerHTML='<i>'+icon+'</i><b>'+esc(label.length>9?"Venue":label)+'</b>';nav.appendChild(btn);bindNavButtons()}
function trackAppEvent(venueId,type,metadata){if(!SUPABASE_URL||!SUPABASE_KEY||!authState)return;functionRequest("app-event-ingest",{venue_id:venueId||null,event_type:type,device_id:getDeviceId(),session_id:getSessionId(),interaction_visibility:interactionVisibility(),display_name:accountPrefs.display_name||"",avatar_url:accountPrefs.avatar_url||"",metadata:metadata||{}}).catch(function(){})}
function trackAppHeartbeat(type){trackAppEvent(null,type||"heartbeat",{page:active,app_version:APP_VERSION})}
function loadDeviceProfile(){if(!SUPABASE_URL||!SUPABASE_KEY)return Promise.resolve(profileSummary);return fetch(SUPABASE_URL+"/functions/v1/device-profile-summary",{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_KEY},body:JSON.stringify({device_id:getDeviceId()})}).then(function(res){if(!res.ok)throw new Error("profile failed");return res.json()}).then(function(data){profileSummary=data.profile||null;cacheState.setProfileSummary(profileSummary);if(active==="profilePage")renderProfile();return profileSummary}).catch(function(){return profileSummary})}
function loadAuthState(){if(!supabaseClient||!supabaseClient.auth)return Promise.resolve(authState);return supabaseClient.auth.getSession().then(function(res){var session=res.data&&res.data.session,user=session&&session.user;authAccessToken=session&&session.access_token||null;appState.auth.accessToken=authAccessToken;if(user&&user.is_anonymous){return supabaseClient.auth.signOut().then(function(){authState=null;authAccessToken=null;appState.auth.accessToken=null;applyPermissions(null);cacheState.clearAuthState();stopLiveLocationWatch();renderAll();return null})}authState=user?{id:user.id,email:user.email||"",isAnonymous:false,updated_at:new Date().toISOString()}:null;if(authState)cacheState.setAuthState(authState);else{cacheState.clearAuthState();applyPermissions(null);stopLiveLocationWatch()}if(authState){return accountRequest("claim",{favorites:favs,preferences:accountPrefs}).then(function(){trackAppHeartbeat("app_open");maybeCapturePresence("foreground");startLiveLocationWatch();loadRewardSummary();loadDeviceProfile();renderAll();return authState}).catch(function(){trackAppHeartbeat("app_open");maybeCapturePresence("foreground");startLiveLocationWatch();renderAll();return authState})}renderAll();return authState}).catch(function(){renderAll();return authState})}
function submitEmailAuth(mode){if(!supabaseClient||!supabaseClient.auth)return showToast("Account service unavailable");var email=($("#authEmail")&&$("#authEmail").value||"").trim().toLowerCase(),password=$("#authPassword")&&$("#authPassword").value||"",name=($("#authName")&&$("#authName").value||"").trim().slice(0,32);if(!email||password.length<6)return showToast("Enter email and 6+ character password");showToast(mode==="signup"?"Creating account...":"Signing in...");var task=mode==="signup"?supabaseClient.auth.signUp({email:email,password:password,options:{data:{display_name:name}}}):supabaseClient.auth.signInWithPassword({email:email,password:password});return task.then(function(res){if(res.error)throw res.error;if(!res.data.session)return showToast("Check your email to finish sign in");authAccessToken=res.data.session.access_token;appState.auth.accessToken=authAccessToken;authState={id:res.data.user.id,email:res.data.user.email||email,isAnonymous:false,updated_at:new Date().toISOString()};cacheState.setAuthState(authState);if(name&&!accountPrefs.display_name)accountPrefs.display_name=name;return accountRequest("claim",{favorites:favs,preferences:accountPrefs})}).then(function(){trackAppHeartbeat("app_open");maybeCapturePresence("foreground");startLiveLocationWatch();loadRewardSummary();loadDeviceProfile();renderAll();showToast(mode==="signup"?"Welcome to LineUp":"Signed in")}).catch(function(err){showToast(err&&err.message?err.message:"Account sign in failed")})}
function startAccountSession(){return submitEmailAuth("signup")}
function signOutAccount(){if(!supabaseClient||!supabaseClient.auth)return;return supabaseClient.auth.signOut().finally(function(){authState=null;authAccessToken=null;appState.auth.accessToken=null;applyPermissions(null);stopLiveLocationWatch();accountPrefs={interaction_visibility:"anonymous",display_name:"",avatar_url:"",profile_setup_completed:false,notification_pref:"unset",location_pref:"unset"};favs=[];saveFavs();cacheState.clearSignedInAccountCache();profileView="home";active="livePage";appState.ui.profileView=profileView;appState.ui.activePage=active;renderAll();showToast("Signed out")})}
function rewardHeaders(){var headers={"Content-Type":"application/json","apikey":SUPABASE_KEY};if(authAccessToken)headers.Authorization="Bearer "+authAccessToken;return headers}
function accountRequest(action,extra){if(!SUPABASE_URL||!SUPABASE_KEY||!authAccessToken)return Promise.reject(new Error("Account session required"));return accountService.request(action,extra).then(function(data){if(data.user){authState={id:data.user.id,email:data.user.email||authState&&authState.email||"",isAnonymous:!!data.user.is_anonymous,updated_at:new Date().toISOString()};cacheState.setAuthState(authState)}if(data.preferences){accountPrefs=Object.assign({},accountPrefs,data.preferences);cacheState.setAccountPrefs(accountPrefs)}if(data.permissions)applyPermissions(data.permissions);if(data.favorites){favs=data.favorites;saveFavs();renderAll()}return data})}
function rewardRequest(action,extra){if(!SUPABASE_URL||!SUPABASE_KEY)return Promise.reject(new Error("Rewards offline"));return rewardService.request(action,extra).then(function(data){if(data.summary){rewardSummary=data.summary;cacheState.setRewardSummary(rewardSummary);if(active==="profilePage")renderProfile()}return data})}
function loadRewardSummary(){return rewardRequest("summary").then(function(data){return data.summary}).catch(function(){return rewardSummary})}
function hasGeo(){return !!navigator.geolocation}
function getCurrentGeo(){return new Promise(function(resolve,reject){if(!hasGeo())return reject(new Error("location unavailable"));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:9000,maximumAge:60000})})}
function getFreshPosition(maxAge){if(lastPosition&&Date.now()-lastPosition.t<maxAge)return Promise.resolve(lastPosition.raw);return getCurrentGeo().then(function(pos){lastPosition={raw:pos,t:Date.now()};return pos})}
function sendLocationIngest(action,venueId,pos,extra){var coords=pos.coords||{};return locationService.sendLocationIngest(Object.assign({action:action,venue_id:venueId||null,lat:coords.latitude,lng:coords.longitude,accuracy_m:Math.round(coords.accuracy||0),interaction_visibility:interactionVisibility(),display_name:accountPrefs.display_name||"",avatar_url:accountPrefs.avatar_url||""},extra||{}))}
function savePresenceState(state){presenceState=state;cacheState.setPresenceState(state)}
function presenceCopy(){if(locationBusy)return{title:"Checking location",detail:"Waiting for your phone"};if(!hasGeo())return{title:"Location unavailable",detail:"Use the native app build"};if(!presenceState)return{title:"Off",detail:"Tap to enable while using"};if(presenceState.nearest_venue_name)return{title:"On while using",detail:presenceState.nearest_venue_name+" · "+Math.round(presenceState.nearest_distance_m||0)+"m"};return{title:"On while using",detail:"Ready for verified signals"}}
function capturePresence(source,venueId,silent){if(locationBusy)return Promise.resolve(null);locationBusy=true;appState.ui.locationBusy=true;if(!silent)showToast("Checking location...");if(active==="profilePage")renderProfile();return getFreshPosition(0).then(function(pos){return sendLocationIngest("presence",venueId||null,pos,{source:source||"foreground"})}).then(function(data){savePresenceState({enabled:true,nearest_venue_id:data.nearest_venue_id,nearest_venue_name:data.nearest_venue_name,nearest_distance_m:data.nearest_distance_m,area:data.area,updated_at:new Date().toISOString()});accountPrefs.location_pref="enabled";cacheState.setAccountPrefs(accountPrefs);lastPresenceAt=Date.now();appState.location.lastPresenceAt=lastPresenceAt;if(!silent)showToast(data.nearest_venue_name?"Near "+data.nearest_venue_name:"Location enabled");return data}).catch(function(){if(!silent)showToast("Location not enabled");return null}).finally(function(){locationBusy=false;appState.ui.locationBusy=false;if(active==="profilePage")renderProfile()})}
function liveLocationAllowed(){return !!(authState&&hasGeo()&&(accountPrefs.location_pref==="enabled"||presenceState))}
function handleLivePosition(pos,source){if(!liveLocationAllowed()||document.visibilityState==="hidden"||liveLocationSending)return;if(Date.now()-liveLocationLastSent<35000)return;liveLocationSending=true;appState.ui.liveLocationSending=true;liveLocationLastSent=Date.now();appState.location.liveLocationLastSent=liveLocationLastSent;lastPosition={raw:pos,t:Date.now()};appState.location.lastPosition=lastPosition;sendLocationIngest("presence",null,pos,{source:source||"live_watch"}).then(function(data){savePresenceState({enabled:true,nearest_venue_id:data.nearest_venue_id,nearest_venue_name:data.nearest_venue_name,nearest_distance_m:data.nearest_distance_m,area:data.area,updated_at:new Date().toISOString()});accountPrefs.location_pref="enabled";cacheState.setAccountPrefs(accountPrefs);lastPresenceAt=Date.now();appState.location.lastPresenceAt=lastPresenceAt;if(active==="profilePage")renderProfile()}).catch(function(){}).finally(function(){liveLocationSending=false;appState.ui.liveLocationSending=false})}
function startLiveLocationWatch(force){if(liveLocationWatchId!=null||!authState||!hasGeo()||document.visibilityState==="hidden")return;if(!force&&!liveLocationAllowed()){if(navigator.permissions&&navigator.permissions.query){navigator.permissions.query({name:"geolocation"}).then(function(p){if(p.state==="granted")startLiveLocationWatch(true)}).catch(function(){startLiveLocationWatch(true)})}else startLiveLocationWatch(true);return}if(force&&accountPrefs.location_pref!=="enabled"){accountPrefs.location_pref="enabled";cacheState.setAccountPrefs(accountPrefs)}liveLocationWatchId=navigator.geolocation.watchPosition(function(pos){handleLivePosition(pos,"live_watch")},function(){stopLiveLocationWatch()},{enableHighAccuracy:true,timeout:12000,maximumAge:15000});appState.location.liveLocationWatchId=liveLocationWatchId}
function stopLiveLocationWatch(){if(liveLocationWatchId==null||!hasGeo())return;navigator.geolocation.clearWatch(liveLocationWatchId);liveLocationWatchId=null;liveLocationSending=false;appState.location.liveLocationWatchId=null;appState.ui.liveLocationSending=false}
function checkInCurrent(){if(!current)return;if(locationBusy)return;var venueName=current.name;locationBusy=true;appState.ui.locationBusy=true;showToast("Verifying check-in...");getFreshPosition(0).then(function(pos){return sendLocationIngest("check_in",current.id,pos,{source:"check_in"})}).then(function(data){if(data.verified){awardReward("checkin",venueName,{checkin_id:data.checkin&&data.checkin.id});recordActivity("Verified check-in",venueName+" · +15 pts");showToast("Verified at "+venueName);loadSupabaseStatus();loadDeviceProfile();if(authState)accountRequest("claim",{favorites:favs}).catch(function(){})}else showToast("Too far away to verify")}).catch(function(){showToast("Location check failed")}).finally(function(){locationBusy=false;appState.ui.locationBusy=false;if(current)renderDetail()})}
function maybeCapturePresence(source){if(!authState||!hasGeo()||locationBusy)return Promise.resolve(null);if(document.visibilityState&&document.visibilityState!=="visible")return Promise.resolve(null);if(Date.now()-lastPresenceAt<3*60000)return Promise.resolve(null);if(accountPrefs.location_pref==="enabled"||presenceState)return capturePresence(source||"foreground",null,true);if(navigator.permissions&&navigator.permissions.query){return navigator.permissions.query({name:"geolocation"}).then(function(p){return p.state==="granted"?capturePresence(source||"foreground",null,true):null}).catch(function(){return capturePresence(source||"foreground",null,true)})}return capturePresence(source||"foreground",null,true)}
document.addEventListener("visibilitychange",function(){if(document.visibilityState==="visible"){trackAppHeartbeat("app_resume");maybeCapturePresence("resume");startLiveLocationWatch()}else stopLiveLocationWatch()});
function functionRequest(name,body,headers){return lineupApi.functionRequest(name,body,headers)}
function venueStatusIngest(id,patch,note){var b=BARS.find(x=>x.id===id),next=patch||{};if(!b)return Promise.reject(new Error("Unknown venue"));return functionRequest("venue-status-ingest",{venue_id:id,crowd_level:next.lvl||b.lvl,wait_minutes:next.wait==null?(b.wait||0):next.wait,cover_amount:next.coverActive?(next.cover||b.cover):null,cover_active:!!next.coverActive,event:next.event==null?(b.event||null):next.event,note:note||"In-app staff control",device_id:getDeviceId()},rewardHeaders())}
function syncVenueAdminToSupabase(id,patch){if(!canAdminVenue(id))return Promise.reject(new Error("Venue role required"));return venueStatusIngest(id,patch,"In-app staff control").then(function(data){if(data&&data.live_status)applyRemoteVenue(data.live_status);return loadSupabaseStatus()})}
function logo(b,cls){var src=ASSET_LOGOS[b.logo];return '<div class="logo '+(cls||'')+'">'+(src?'<img src="'+src+'" alt="">':'<span class="logotext">'+esc(b.logo||b.name.slice(0,2))+'</span>')+'</div>'}
function confColor(c){return c==="high"?"var(--high)":c==="medium"?"var(--medium)":"var(--low)"}function level(b){return LEVELS[b.lvl]}function isFav(id){return favs.indexOf(id)>-1}
function localConfidenceScore(b){var base=b.conf==="high"?74:b.conf==="medium"?54:30,src=(b.sources||[]).join(" ").toLowerCase(),boost=0;if(src.indexOf("owner")>-1)boost+=18;if(src.indexOf("venue")>-1||src.indexOf("staff")>-1)boost+=16;if(src.indexOf("verified")>-1||src.indexOf("check")>-1)boost+=12;if(src.indexOf("scout")>-1)boost+=10;if(src.indexOf("report")>-1)boost+=8;if(src.indexOf("app")>-1||src.indexOf("directions")>-1)boost+=5;if(src.indexOf("historical")>-1||src.indexOf("typical")>-1)boost+=3;var fresh=b.fresh==null?90:b.fresh,decay=fresh<10?8:fresh<30?3:fresh>120?-18:fresh>60?-10:0,inputs=Math.min(10,(b.confSignals||0)*2);return base+boost+decay+inputs}
function confidenceScore(b){return Math.max(0,Math.min(100,Math.round(b.confScore==null?localConfidenceScore(b):b.confScore)))}
function signalState(b){var src=(b.sources||[]).join(" ").toLowerCase(),fresh=b.fresh==null?999:b.fresh,inputs=Number(b.confSignals||0),staff=src.indexOf("owner")>-1||src.indexOf("venue")>-1||src.indexOf("staff")>-1,verified=src.indexOf("verified")>-1||src.indexOf("check")>-1||src.indexOf("nearby")>-1||src.indexOf("scout")>-1,baseline=src.indexOf("historical")>-1||src.indexOf("typical")>-1||src.indexOf("baseline")>-1;if(staff&&fresh<=90)return{key:"staff",label:"Fresh staff update",detail:freshText(b),tone:"high",mode:"Venue-confirmed read"};if(verified&&fresh<=90)return{key:"verified",label:"Verified nearby reports",detail:freshText(b),tone:"high",mode:"Location-backed read"};if(b.conf==="low"||fresh>120||inputs===0)return{key:"low",label:"Low recent data",detail:"Showing typical pattern",tone:"low",mode:"Needs fresh reports"};if(baseline||fresh>60)return{key:"typical",label:"Typical for now",detail:freshText(b),tone:"medium",mode:"Historical pattern"};return{key:"recent",label:"Recent live signals",detail:freshText(b),tone:b.conf||"medium",mode:"Crowd-sourced read"}}
function confidenceLabel(b){return signalState(b).label}
function confidenceDetail(b){return signalState(b).detail}
function confidenceTone(b){return signalState(b).tone}
function closeText(b){var now=new Date(new Date().toLocaleString("en-US",{timeZone:"America/Phoenix"})),m=now.getHours()*60+now.getMinutes(),o=b.open*60,c=b.close*60,overnight=c<=o,open=overnight?(m>=o||m<c):(m>=o&&m<c);if(!open)return "Closed · Opens "+hour(b.open);var diff=(overnight&&m>=o?c+1440-m:c-m);if(diff<=45)return "Closing soon · "+diff+"m";if(diff<=120)return "Closes in "+Math.floor(diff/60)+"h "+(diff%60)+"m";return "Closes at "+hour(b.close)}
function showToast(t){var el=$("#toast");el.textContent=t;el.style.opacity=1;el.style.transform="translateX(-50%)";clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.style.opacity=0;el.style.transform="translateX(-50%) translateY(20px)"},2200)}
function freshText(b){return b.fresh<1?"Updated just now":"Updated "+b.fresh+" min ago"}
function lineLeap(b){return b.lineLeap||("https://tickets.lineleap.com/search?search="+encodeURIComponent(b.name+" Tucson"))}
function liveIcon(){return '<svg class="heartbeat" viewBox="0 0 32 24" aria-hidden="true"><path class="trace" d="M2 13h6l3-8 5 16 4-10 3 2h7"/></svg>'}
function rewardState(){return{points:0,earnedSkip:false,redeemedSkips:0,reportDay:"",reportsToday:0}}
function recordActivity(title,detail){activityLog.unshift({title:title,detail:detail,at:new Date().toISOString()});activityLog=activityLog.slice(0,12);cacheState.setActivityLog(activityLog)}
function awardReward(kind,label,extra){return rewardRequest("award",Object.assign({kind:kind,label:label||""},extra||{})).then(function(data){if(data.capped)return showToast(data.message||"Daily reward points are maxed");var pts=data.awarded&&data.awarded.points||0;if(kind!=="checkin")recordActivity(kind==="verified_report"?"Verified report":"Report submitted",(label||"LineUp")+" · +"+pts+" pts");showToast("+"+pts+" LineUp points")}).catch(function(){showToast("Rewards need a secure connection")})}
function redeemSkip(){return rewardRequest("redeem").then(function(data){var code=data.redemption&&data.redemption.code;recordActivity("LineUp Skip redeemed",code?"Code "+code:"Reward issued");renderProfile();showToast("LineUp Skip added")}).catch(function(err){var data=err&&err.data;if(data&&data.summary){rewardSummary=data.summary;cacheState.setRewardSummary(rewardSummary);renderProfile();return showToast("Keep earning toward your LineUp Skip")}showToast("Rewards need a secure connection")})}
function rewardViewState(){var local=rewardState();if(rewardSummary)return{points:Number(rewardSummary.balance||0),redeemed:Number(rewardSummary.redeemed_skips||0),goal:Number(rewardSummary.reward_goal||REWARD_GOAL),server:true,events:rewardSummary.recent_events||[],redemptions:rewardSummary.recent_redemptions||[]};return{points:local.points,redeemed:local.redeemedSkips||0,goal:REWARD_GOAL,server:false,events:[],redemptions:[]}}
function renderRewards(){return renderRewardsHtml({rewardViewState:rewardViewState})}
function accountLabel(){return authState?authState.isAnonymous?"LineUp account":"Signed account":"Account required"}
function interactionVisibility(){return accountPrefs.interaction_visibility==="public"?"public":"anonymous"}
function syncAccountPrefs(silent){cacheState.setAccountPrefs(accountPrefs);if(!authState)return Promise.resolve();return accountRequest("update_profile",{preferences:accountPrefs}).then(function(){if(!silent)showToast("Account settings saved")}).catch(function(){if(!silent)showToast("Settings saved on this phone")})}
function setInteractionVisibility(mode){accountPrefs.interaction_visibility=mode==="public"?"public":"anonymous";syncAccountPrefs(false);accountNeedsSetup()?renderSetupGate():renderProfile()}
function saveDisplayName(){var v=($("#displayNameField")&&$("#displayNameField").value||"").trim().slice(0,32);accountPrefs.display_name=v;syncAccountPrefs(false);renderProfile()}
function accountNeedsSetup(){return authState&&!accountPrefs.profile_setup_completed}
function publicName(){return interactionVisibility()==="anonymous"?"Anonymous User":(accountPrefs.display_name||"LineUp User")}
function profileAvatar(){var show=interactionVisibility()==="public"&&accountPrefs.avatar_url;return show?'<img src="'+esc(accountPrefs.avatar_url)+'" alt="">':(interactionVisibility()==="anonymous"?"A":"L")}
function prefStatus(kind){if(kind==="notification"&&"Notification" in window)return Notification.permission==="granted"?"enabled":Notification.permission==="denied"?"denied":accountPrefs.notification_pref||"unset";return accountPrefs[kind+"_pref"]||"unset"}
function handleAvatarFile(input){var file=input.files&&input.files[0];if(!file)return;if(String(file.type||"").indexOf("image/")!==0)return showToast("Choose an image file");if(file.size>250000)return showToast("Use a smaller profile image");var r=new FileReader();r.onload=function(){accountPrefs.avatar_url=String(r.result||"");cacheState.setAccountPrefs(accountPrefs);renderProfile()};r.readAsDataURL(file)}
function requestNotifications(){if(!("Notification" in window)){accountPrefs.notification_pref="disabled";syncAccountPrefs(false);return showToast("Notifications unavailable")}return Notification.requestPermission().then(function(p){accountPrefs.notification_pref=p==="granted"?"enabled":p==="denied"?"denied":"unset";syncAccountPrefs(false);renderProfile();showToast(p==="granted"?"Notifications enabled":"Notifications not enabled")})}
function requestSetupLocation(){return capturePresence("setup",null,false).then(function(data){accountPrefs.location_pref=data?"enabled":"denied";return syncAccountPrefs(true)}).then(function(){renderProfile()})}
function saveSetup(){var name=($("#setupName")&&$("#setupName").value||"").trim().slice(0,32);if(!name)return showToast("Add a display name");accountPrefs.display_name=name;accountPrefs.profile_setup_completed=true;accountPrefs.terms_accepted=true;accountPrefs.data_policy_seen=true;cacheState.setAccountPrefs(accountPrefs);return accountRequest("claim",{favorites:favs,preferences:accountPrefs}).then(function(){profileView=selectProfileView(appState,"home");renderAll();showToast("Account ready")}).catch(function(){showToast("Could not save setup")})}
function renderAccountGate(){var root=$("#livePage");$all(".page").forEach(p=>p.classList.toggle("active",p.id==="livePage"));$all(".navbtn").forEach(n=>n.classList.remove("on"));document.body.dataset.page="accountGate";root.innerHTML=renderAccountGateHtml()}
function renderSetupGate(){var root=$("#livePage"),mode=interactionVisibility(),favoritesHtml=activeBars().slice(0,10).map(b=>`<button class="${isFav(b.id)?"on":""}" onclick="toggleFav('${b.id}')">${esc(b.name)}</button>`).join("");$all(".page").forEach(p=>p.classList.toggle("active",p.id==="livePage"));$all(".navbtn").forEach(n=>n.classList.remove("on"));document.body.dataset.page="setupGate";root.innerHTML=renderSetupGateHtml({mode:mode,avatarHtml:profileAvatar(),displayName:accountPrefs.display_name||"",favoritesHtml:favoritesHtml})}
function activeBars(){return BARS.filter(b=>b.status==="active"&&!b.deprecated)}
function barsInArea(){return activeBars().filter(b=>b.area===area)}
function areaName(v){return v==="main_gate"?"University":"Downtown"}
function coverLabel(b){return b.coverActive&&b.cover&&b.cover!=="$0"?b.cover:""}
function sortedByCrowd(list){return [...list].sort((a,b)=>LEVELS[b.lvl].pct-LEVELS[a.lvl].pct||b.wait-a.wait)}
function openMaps(b){trackAppEvent(b.id,"directions_tap",{area:b.area});window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(b.mapQuery||b.name+" "+b.address),"_blank","noopener")}
function renderBar(b){return renderBarCard(b,{level:level,closeText:closeText,isFavorite:isFav,signalState:signalState,confColor:confColor,logo:logo,colors:COLORS,svg:SVG})}
function cap(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function areaPulseCopy(list){return dashboardPulseCopy({list:list,area:area,areaName:areaName,isFavorite:isFav})}
function renderLive(){var list=barsInArea().sort((a,b)=>(isFav(b.id)-isFav(a.id))||a.name.localeCompare(b.name)),pulse=areaPulseCopy(list);$("#tabU").className=area==="main_gate"?"on":"";$("#tabP").className=area==="fourth_downtown"?"on":"";$("#livePage").innerHTML=renderLiveDashboard({list:list,pulse:pulse,svg:SVG,renderBar:renderBar});bindCards()}
function bindCards(){$all(".barcard,.rankItem").forEach(c=>c.onclick=function(){openDetail(c.dataset.id)});$all(".fav").forEach(b=>b.onclick=function(e){e.stopPropagation();toggleFav(b.dataset.fav)})}
function toggleFav(id){var i=favs.indexOf(id),on=i<0;if(i>=0){favs.splice(i,1);trackAppEvent(id,"favorite_remove");showToast("Removed from favorites")}else{favs.unshift(id);trackAppEvent(id,"favorite_add");showToast("Added to favorites")}saveFavs();renderAll();if(authState)accountRequest("set_favorite",{venue_id:id,favorited:on}).catch(function(){})}
function setPage(id){active=selectPage(appState,id,canUseVenueControls);window.scrollTo({top:0,behavior:"auto"});$all(".page").forEach(p=>p.classList.toggle("active",p.id===active));$all(".navbtn").forEach(n=>n.classList.toggle("on",n.dataset.page===active));renderAll()}
function renderFavs(){setPage("livePage")}
function renderFallbackMap(){$("#mapBox").innerHTML=fallbackMapHtml({bars:activeBars(),userCoords:USER_COORDS,colors:COLORS});bindMap()}
function renderMap(){if(mapController)return mapController.render();if(mapInstance){mapInstance.remove();mapInstance=null;appState.map.mapInstance=null}mapMarkers=[];appState.map.markers=mapMarkers;$("#mapPage").innerHTML=mapShellHtml();if(!MAPBOX_TOKEN){renderFallbackMap();$("#mapBox").insertAdjacentHTML("afterend",mapUnavailableHtml());return}loadMapbox().then(initRealMap).catch(function(){renderFallbackMap();showToast("Mapbox failed to load")})}
function loadMapbox(){if(mapboxReady)return mapboxReady;mapboxReady=import("mapbox-gl").then(function(mod){mapboxgl=mod.default||mod;appState.map.mapboxgl=mapboxgl;return mapboxgl});appState.map.mapboxReady=mapboxReady;return mapboxReady}
function initRealMap(){var box=$("#mapBox");if(!box)return;box.innerHTML="";mapboxgl.accessToken=MAPBOX_TOKEN;mapInstance=new mapboxgl.Map({container:"mapBox",style:"mapbox://styles/mapbox/dark-v11",center:MAP_CENTER,zoom:13.6,pitch:28,bearing:-10,attributionControl:true});appState.map.mapInstance=mapInstance;mapInstance.addControl(new mapboxgl.NavigationControl({showCompass:false}),"top-right");mapInstance.on("load",function(){mapInstance.addSource("user-geofence",{type:"geojson",data:circlePolygon(USER_COORDS,230,64)});mapInstance.addLayer({id:"user-geofence-fill",type:"fill",source:"user-geofence",paint:{"fill-color":"#12E0C4","fill-opacity":0.12}});mapInstance.addLayer({id:"user-geofence-line",type:"line",source:"user-geofence",paint:{"line-color":"#12E0C4","line-width":2,"line-opacity":0.75}});activeBars().forEach(function(b){var marker=createVenueMarker({mapboxgl:mapboxgl,map:mapInstance,bar:b,level:level,escHtml:esc,onTap:function(){trackAppEvent(b.id,"map_pin_tap",{map:"mapbox"});openDetail(b.id)}});mapMarkers.push(marker)});appState.map.markers=mapMarkers;mapInstance.resize()});box.insertAdjacentHTML("beforeend",'<div class="maphint">Drag, zoom, and tap a pin for venue details</div>')}
function renderStats(){if(intelMode==="compare")intelMode="confidence";var live=activeBars(),list=sortedByCrowd(live),shortest=[...live].sort((a,b)=>a.wait-b.wait)[0],top=list[0],activeCovers=live.filter(b=>coverLabel(b)).length,body=intelMode==="tonight"?renderIntelTonight(top,shortest,activeCovers):intelMode==="timing"?renderIntelTiming():renderIntelConfidence();$("#statsPage").innerHTML=`<div class="sectionlabel">NIGHT INTEL</div><div class="seg intelTabs"><button class="${intelMode==="tonight"?"on":""}" onclick="intelMode='tonight';renderStats()">Tonight</button><button class="${intelMode==="timing"?"on":""}" onclick="intelMode='timing';renderStats()">Timing</button><button class="${intelMode==="confidence"?"on":""}" onclick="intelMode='confidence';renderStats()">Signals</button></div><div class="intelBody">${body}<div class="card intelNote"><b>Why this exists</b><p class="muted intelCopy">Intel answers timing, confidence, and value questions without making users reread the live bar list.</p></div></div>`}
function renderIntelTonight(top,shortest,activeCovers){return '<div class="card intelHero"><div class="intelTop"><b>Best live move</b><span class="muted">Right now</span></div><div class="intelMove"><div class="intelVenue"><b>'+esc(top.name)+'</b><div class="muted">'+level(top).label+' · '+top.event+'</div></div><div class="intelMetric">'+top.wait+' min</div></div></div><div class="intelGrid"><div class="intelTile"><span class="muted">Shortest line</span><div><b>'+esc(shortest.name)+'</b><small>'+(shortest.wait?shortest.wait+" min":"No line")+'</small></div></div><div class="intelTile"><span class="muted">Cover alerts</span><div><b>'+(activeCovers||"None")+'</b><small>'+(activeCovers?"Active tonight":"Hidden unless enabled")+'</small></div></div></div>'}
function renderIntelTiming(){return '<div class="card intelHero"><div class="intelTop"><b>When to move</b><span class="muted">Tonight</span></div><div class="timeGrid"><div class="timeSlot"><b>9 PM</b><span>Easy</span></div><div class="timeSlot"><b>10 PM</b><span>Rising</span></div><div class="timeSlot"><b>11 PM</b><span>Peak</span></div><div class="timeSlot"><b>12 AM</b><span>Lines</span></div></div><div class="chart">'+spark()+'</div></div><div class="intelGrid"><div class="intelTile"><span class="muted">Leave before</span><div><b>10:35 PM</b><small>Best odds of short lines</small></div></div><div class="intelTile"><span class="muted">Peak pressure</span><div><b>11 PM-12 AM</b><small>Expect cover + waits</small></div></div></div>'}
function renderIntelConfidence(){var live=activeBars(),staff=live.filter(b=>signalState(b).key==="staff").length,verified=live.filter(b=>signalState(b).key==="verified").length,typical=live.filter(b=>signalState(b).key==="typical"||signalState(b).key==="recent").length,low=live.filter(b=>signalState(b).key==="low").length;return '<div class="card intelHero"><b>Read quality</b><p class="muted intelCopy">LineUp labels each read by source quality and freshness, so users know whether they are seeing a live confirmation or a typical pattern for this time.</p><div class="signalGrid"><div class="timeSlot"><b>'+staff+'</b><span>Fresh staff</span></div><div class="timeSlot"><b>'+verified+'</b><span>Nearby reports</span></div><div class="timeSlot"><b>'+typical+'</b><span>Typical now</span></div><div class="timeSlot"><b>'+low+'</b><span>Needs reports</span></div></div></div><div class="card intelNote"><b>How reads improve</b><p class="muted intelCopy">Fresh staff updates, verified nearby reports, check-ins, app demand, and historical baselines are blended together. Older signals fade so the app can return to “Typical for now” instead of overstating stale activity.</p></div>'}
function renderStatsCompact(){var live=activeBars(),list=sortedByCrowd(live),shortest=[...live].sort((a,b)=>a.wait-b.wait)[0],top=list[0],fresh=Math.min.apply(null,live.map(b=>b.fresh)),bestSig=signalState(top);return '<div class="intelGrid"><div class="intelTile"><span class="muted">Best move</span><div><b>'+esc(top.name)+'</b><small>'+top.wait+' min · '+level(top).label+'</small></div></div><div class="intelTile"><span class="muted">Shortest line</span><div><b>'+esc(shortest.name)+'</b><small>'+(shortest.wait?shortest.wait+" min":"No line")+'</small></div></div><div class="intelTile"><span class="muted">Freshest read</span><div><b>'+fresh+' min</b><small>Latest venue signal</small></div></div><div class="intelTile"><span class="muted">Read quality</span><div><b>'+esc(bestSig.label)+'</b><small>'+esc(bestSig.mode)+'</small></div></div></div>'}
function ownerRequest(){return fetch(SUPABASE_URL+"/functions/v1/owner-dashboard",{method:"POST",headers:rewardHeaders(),body:JSON.stringify({})}).then(function(res){return res.json().then(function(data){if(!res.ok)throw new Error(data.error||"Owner dashboard failed");return data})}).then(function(data){ownerData=data;appState.backend.ownerData=data;return data})}
function ownerAction(action,extra){if(!isOwnerAccount())return Promise.reject(new Error("Owner account required"));return functionRequest("owner-actions",Object.assign({action:action,device_id:getDeviceId()},extra||{}),rewardHeaders())}
function ownerControlVenues(){var rows=ownerData&&ownerData.venue_activity&&ownerData.venue_activity.length?ownerData.venue_activity:activeBars();return rows.slice().sort(function(a,b){return String(a.name).localeCompare(String(b.name))})}
function ownerVenueOptions(selected){return ownerControlVenues().map(function(v){var state=v.status&&v.status!=="active"?" · "+v.status:"";return '<option value="'+esc(v.id)+'" '+(v.id===selected?"selected":"")+'>'+esc(v.name+state)+'</option>'}).join("")}
function ownerPublishVenue(){if(ownerController)return ownerController.publishVenue();var id=$("#ownerVenue").value,b=BARS.find(v=>v.id===id),wait=parseInt($("#ownerWait").value,10),cover=$("#ownerCover").value,event=$("#ownerEvent").value.trim(),lvl=$("#ownerCrowd").value;if(!b)return;showToast("Publishing owner update...");ownerAction("venue_live_update",{venue_id:id,crowd_level:lvl,wait_minutes:isNaN(wait)?0:wait,cover_amount:cover||null,cover_active:!!cover,event:event||null,note:"Owner control update"}).then(function(){return loadSupabaseStatus()}).then(function(){return ownerRequest()}).then(function(){renderOwnerDashboard();showToast("Owner update live")}).catch(function(err){showToast(err.message||"Owner update failed")})}
function ownerSetVenueStatus(status){return ownerController?ownerController.setVenueStatus(status):null}
function ownerSetRedemption(id,status){return ownerController?ownerController.setRedemption(id,status):null}
function ownerOpenVenue(id){return ownerController?ownerController.openVenue(id):null}
function ownerCompactRow(title,meta,right){return '<div class="ownerVenueRow"><div><b>'+esc(title)+'</b><span>'+esc(meta)+'</span></div><b>'+esc(right||"")+'</b></div>'}
function renderOwnerVenueDetail(data){$("#sheetcard").innerHTML=renderOwnerVenueDetailHtml(data)}
function refreshOwnerDashboard(){return ownerController?ownerController.refresh():(isOwnerAccount()?ownerRequest().then(renderOwnerDashboard):showToast("Owner account required"))}
function refreshOwnerDashboardSilent(){return ownerController?ownerController.refreshSilent():(active!=="statsPage"||!isOwnerAccount()||document.visibilityState==="hidden"?null:ownerRequest().then(function(){if(active==="statsPage"&&isOwnerAccount())renderOwnerDashboard()}).catch(function(){}))}
function exitOwnerMode(){return ownerController?ownerController.exit():(ownerData=null,appState.backend.ownerData=null,ownerMap&&(ownerMap.remove(),ownerMap=null,appState.map.ownerMap=null),setPage("profilePage"),showToast("Owner tools closed"))}
function ownerSetControlVenue(id){var v=(ownerData&&ownerData.venue_activity||[]).find(x=>x.id===id)||BARS.find(b=>b.id===id);if(!v)return;if($("#ownerCrowd"))$("#ownerCrowd").value=LEVELS[v.crowd_level]?v.crowd_level:(v.lvl||"slow");if($("#ownerWait"))$("#ownerWait").value=v.wait_minutes==null?(v.wait||0):v.wait_minutes;if($("#ownerEvent"))$("#ownerEvent").value=v.event||""}
function renderOwnerDashboard(){var d=ownerData;if(!d){$("#statsPage").innerHTML=loadingOwnerDashboardHtml();refreshOwnerDashboard();return}var first=ownerControlVenues()[0]&&ownerControlVenues()[0].id||activeBars()[0]&&activeBars()[0].id;$("#statsPage").innerHTML=renderOwnerDashboardHtml({data:d,controlVenues:ownerControlVenues(),firstVenueId:first,levels:LEVELS});ownerSetControlVenue(first);initOwnerMap()}
function initOwnerMap(){var box=$("#ownerMap"),d=ownerData;if(!box||!d)return;if(ownerMap){ownerMap.remove();ownerMap=null;appState.map.ownerMap=null}if(!MAPBOX_TOKEN){box.innerHTML='<div class="mapSetup"><div class="mapSetupCard"><b>Owner map unavailable</b><p class="muted">Mapbox token is required for active-user map tiles.</p></div></div>';return}loadMapbox().then(function(){box.innerHTML="";mapboxgl.accessToken=MAPBOX_TOKEN;ownerMap=new mapboxgl.Map({container:"ownerMap",style:"mapbox://styles/mapbox/dark-v11",center:MAP_CENTER,zoom:13.4,pitch:20,attributionControl:false});appState.map.ownerMap=ownerMap;ownerMap.addControl(new mapboxgl.NavigationControl({showCompass:false}),"top-right");ownerMap.on("load",function(){var activeBounds=new mapboxgl.LngLatBounds();(d.venue_activity||[]).forEach(function(v){if(!Number.isFinite(v.lat)||!Number.isFinite(v.lng))return;var el=document.createElement("button");el.className="mapMarker "+(v.crowd_level||"slow");el.type="button";el.setAttribute("aria-label",v.name);new mapboxgl.Marker({element:el,anchor:"bottom"}).setLngLat([v.lng,v.lat]).addTo(ownerMap)});(d.active_points||[]).forEach(function(p){var el=document.createElement("div");el.className="ownerUserDot "+(p.age_min>15?"dim":"");el.title=(p.precision==="exact_foreground"?"Exact foreground":"Rounded")+" · "+p.nearest_venue_name+" · "+p.age_min+"m ago";new mapboxgl.Marker({element:el,anchor:"center"}).setLngLat([p.lng,p.lat]).addTo(ownerMap);activeBounds.extend([p.lng,p.lat])});if((d.active_points||[]).length)ownerMap.fitBounds(activeBounds,{padding:54,maxZoom:13,duration:0});ownerMap.resize()})}).catch(function(){box.innerHTML='<div class="mapSetup"><div class="mapSetupCard"><b>Owner map failed</b><p class="muted">Private stats still loaded below.</p></div></div>'})}
function openProfileView(view){profileView=selectProfileView(appState,view);active=appState.ui.activePage;setPage("profilePage")}
function profileBack(){profileView=selectProfileView(appState,"home");renderProfile()}
function legalCopy(kind){return profileLegalCopy(kind)}
function showLegalSheet(kind){$("#reportSheet").classList.add("open");$("#sheetcard").innerHTML=renderLegalSheetHtml(kind)}
function renderProfile(){$("#profilePage").innerHTML=renderProfilePageHtml(profileView,{svg:SVG,accountPrefs:accountPrefs,authState:authState,favs:favs,activeBars:activeBars,isFav:isFav,interactionVisibility:interactionVisibility,publicName:publicName,profileAvatar:profileAvatar,rewardViewState:rewardViewState,profileSummary:profileSummary,presenceState:presenceState,presenceCopy:presenceCopy,prefStatus:prefStatus,cap:cap})}
function renderHighlightsPage(){$("#highlightsPage").innerHTML='<div class="sectionlabel">PULSE PLANNER</div>'+renderHighlights("page");bindCards()}
function setPulseVibe(v){pulseVibe=selectPulseVibe(appState,v);renderHighlightsPage()}
function vibeOptions(){return[{id:"chill",name:"Chill night",desc:"Easy with friends",tags:["chill","friends","patio","pub","speakeasy"]},{id:"dance",name:"High energy",desc:"Dance, DJ, loud room",tags:["dance","lively","edm","late","drag"]},{id:"patio",name:"Patio route",desc:"Outdoor / open-air feel",tags:["patio","rooftop","tiki","friends"]},{id:"value",name:"Easy-entry move",desc:"Lower friction tonight",tags:["no_cover","food","casual","friends"]}]}
function planScore(b,tags){var scene=(b.scenes||[]).filter(s=>tags.indexOf(s)>-1).length*24,live=b.lvl==="packed"?18:b.lvl==="busy"?24:b.lvl==="slow"?16:6,line=b.wait===0?18:b.wait<=10?14:b.wait<=20?8:-8,confidence=Math.round(confidenceScore(b)/10);return scene+live+line+confidence}
function pulseReason(b){var l=level(b).label.toLowerCase(),line=b.wait?b.wait+" min line":"no line",sig=signalState(b);return cap(l)+" right now with "+line+". "+esc(b.tag)+" fits this plan. Read quality: "+sig.label.toLowerCase()+"."}
function renderHighlights(mode){var options=vibeOptions(),picked=options.find(v=>v.id===pulseVibe)||options[0],picks=activeBars().map(b=>({bar:b,score:planScore(b,picked.tags)})).sort((a,b)=>b.score-a.score).slice(0,3),intro=mode==="page"?'<div class="pulsecard"><div class="pulseicon">'+SVG.pulseTrend+'</div><div><b>Build the plan, then move.</b><span>Pick the kind of night you want. Pulse uses venue style plus live data to guide the next stop.</span></div></div>':"",intel='<details class="card photoPanel"><summary>Night Intel <span class="muted">For the curious</span></summary><div style="margin-top:12px">'+renderStatsCompact()+'</div></details>';return intro+'<div class="pulsePlan"><div class="vibeGrid">'+options.map(v=>'<button class="vibeBtn '+(pulseVibe===v.id?"on":"")+'" onclick="setPulseVibe(&quot;'+v.id+'&quot;)"><b>'+v.name+'</b><span>'+v.desc+'</span></button>').join("")+'</div><div class="sectionlabel">RECOMMENDED ROUTE</div>'+picks.map((p,i)=>'<article class="card planHero barcard" data-id="'+p.bar.id+'"><div class="planPick"><div class="planRank">'+(i+1)+'</div><div><h3>'+esc(p.bar.name)+'</h3><p class="planReason">'+pulseReason(p.bar)+'</p><div class="planMeta"><span class="planPill hot">'+(p.bar.wait?p.bar.wait+" min":"No line")+'</span><span class="planPill">'+level(p.bar).label+'</span><span class="planPill">'+areaName(p.bar.area)+'</span></div></div></div></article>').join("")+'<div class="card"><b>How Pulse thinks</b><p class="muted intelCopy">Pulse weighs the scene you selected, live crowd level, line wait, and confidence. It should feel like a friend who knows the bars and is watching the night change.</p></div>'+intel+'<div class="sectionlabel">TONIGHT’S EVENTS</div>'+activeBars().filter(b=>b.event).slice(0,4).map(b=>'<div class="card row barcard" data-id="'+b.id+'"><div><b>'+esc(b.name)+'</b><div class="muted">'+esc(b.event)+'</div></div><span class="muted">'+(b.wait?b.wait+" min":"No line")+'</span></div>').join("")+'</div>'}
function openDetail(id){if(barDetailController)return barDetailController.open(id);current=selectDetailVenue(appState,BARS.find(b=>b.id===id),"live");if(current){trackAppEvent(id,"detail_view",{area:current.area,page:active});loadVenueReports(id)}detailTab=appState.ui.detailTab;renderDetail();var el=$("#detail");el.style.transform="";el.scrollTop=0;el.classList.add("open")}
function closeDetail(){if(barDetailController)return barDetailController.close();var el=$("#detail");el.style.transform="";el.classList.remove("open")}
function navigateDetail(toId,dir){
  var el=$("#detail"),stage=el.querySelector(".detailStage"),outX=dir==="left"?"-105%":"105%",inX=dir==="left"?"105%":"-105%";
  if(!stage)return;
  stage.style.transition="transform .2s ease-in, opacity .2s ease-in";stage.style.transform="translateX("+outX+")";stage.style.opacity=".82";
  setTimeout(function(){
    current=selectDetailVenue(appState,BARS.find(b=>b.id===toId),"live");detailTab=appState.ui.detailTab;renderDetail();
    loadVenueReports(toId);
    el.scrollTop=0;stage=el.querySelector(".detailStage");stage.style.transition="none";stage.style.transform="translateX("+inX+")";stage.style.opacity=".82";
    void stage.offsetWidth;
    stage.style.transition="transform .2s ease-out, opacity .2s ease-out";stage.style.transform="translateX(0)";stage.style.opacity="1";
    setTimeout(function(){stage.style.transition="";stage.style.transform="";stage.style.opacity=""},220);
  },200);
}
function detailMiniRow(b){return renderDetailMiniRow(b,{closeText:closeText,coverLabel:coverLabel,svg:SVG})}
function renderDetail(){var b=current;if(!b)return;var reports=reportRows(b.id),el=$("#detail");el.innerHTML=renderDetailHtml({bar:b,reports:reports,detailTab:detailTab,level:level,signalState:signalState,confColor:confColor,colors:COLORS,svg:SVG,logo:logo,isFavorite:isFav,lineLeap:lineLeap,detailMiniRow:detailMiniRow,detailPanel:detailPanel});wrapDetailContent(el)}
function wrapDetailContent(el){var stage=document.createElement("div");stage.className="detailStage";while(el.firstChild)stage.appendChild(el.firstChild);el.appendChild(stage)}
function setDetailTab(tab){return barDetailController?barDetailController.selectTab(tab):(detailTab=selectDetailTab(appState,tab),renderDetail())}
function confidenceBreakdown(b){return renderDetailConfidenceBreakdown(b,{signalState:signalState,escSource:esc})}
function reportRows(id){var remote=REMOTE_REPORTS[id]||[];if(remote.length)return remote;return[{id:"empty",note:"No live reports yet tonight.",seed_time:"",created_at:null,location_verified:false,empty:true,author:{name:"LineUp",avatar_url:"",anonymous:false}}]}
function renderReportRows(reports){return renderDetailReportRows(reports,{levels:LEVELS,svg:SVG})}
function detailPanel(b,reports){return renderDetailPanel(b,reports,{detailTab:detailTab,signalState:signalState,renderHighlights:renderHighlights,spark:spark,cap:cap,confColor:confColor,confidenceBreakdown:confidenceBreakdown,renderReportRows:renderReportRows})}
function spark(){return '<svg viewBox="0 0 300 120" preserveAspectRatio="none"><path d="M0,85 C30,65 38,90 58,76 C82,58 90,70 110,50 C135,22 160,35 183,18 C210,4 230,30 252,26 C275,22 284,56 300,50" fill="none" stroke="var(--packed)" stroke-width="4"/><path d="M0,120 L0,85 C30,65 38,90 58,76 C82,58 90,70 110,50 C135,22 160,35 183,18 C210,4 230,30 252,26 C275,22 284,56 300,50 L300,120 Z" fill="rgba(255,79,123,.14)"/></svg>'}
function openReport(){return reportController?reportController.open():(trackAppEvent(current.id,"report_open"),selectedReportLevel=selectReportLevel(appState,current.lvl),$("#reportSheet").classList.add("open"),renderReportSheet(),capturePresence("report",current.id,true))}
function renderReportSheet(){var b=current;if(!b)return;$("#sheetcard").innerHTML=renderReportSheetHtml({bar:b,presence:presenceCopy(),selectedReportLevel:selectedReportLevel,levels:LEVELS});$("#coverField").value=b.coverActive?b.cover:""}
function setReportCrowd(level){return reportController?reportController.selectCrowd(level):(selectedReportLevel=selectReportLevel(appState,level),renderReportSheet())}
function setLinePreset(v){return reportController?reportController.setLinePreset(v):(($("#lineField")||{}).value=v)}
function closeSheet(){return reportController?reportController.close():$("#reportSheet").classList.remove("open")}
async function submitReport(){var v=parseInt($("#lineField").value,10),cover=$("#coverField").value,note=$("#noteField").value.trim(),patch={lvl:selectedReportLevel,wait:isNaN(v)?current.wait:Math.max(0,Math.min(90,v)),coverActive:!!cover,cover:cover||current.cover},bar=current;closeSheet();showToast("Submitting report...");var result=await syncReportToSupabase(bar,patch,note,false),reportId=result.report&&result.report.id;if(reportId){await loadVenueReports(bar.id);await loadSupabaseStatus();current=selectDetailVenue(appState,BARS.find(b=>b.id===bar.id)||bar,detailTab);awardReward(result.verified?"verified_report":"report",bar.name,{report_id:reportId});showToast(result.verified?"Verified report added":"Report added live")}else{showToast("Report could not sync. Try again.")}if(authState)accountRequest("claim",{favorites:favs}).catch(function(){});loadDeviceProfile();if(current&&$("#detail").classList.contains("open"))renderDetail();renderAll()}
function reportSummary(b,note){var line=b.wait?b.wait+" min line":"no line",crowd=level(b).label.toLowerCase();if(note)return note;return cap(crowd)+" crowd · "+line}
function openAdmin(){setPage("statsPage")}
function setAdminVenue(id){return venueStaffController?venueStaffController.selectVenue(id):(adminVenueId=selectAdminVenue(appState,id),renderAdminSheet())}
function renderAdminSheet(){var ids=isOwnerAccount()?activeBars().map(v=>v.id):assignedVenues().map(v=>v.id);ids=ids.filter(function(id){return BARS.some(function(b){return b.id===id})});if(!ids.length){$("#statsPage").innerHTML=noVenueRoleHtml();return}if(!adminVenueId||ids.indexOf(adminVenueId)<0)adminVenueId=selectAdminVenue(appState,defaultControlVenueId()||ids[0]);var b=BARS.find(x=>x.id===adminVenueId)||BARS.find(x=>x.id===ids[0]);adminVenueId=selectAdminVenue(appState,b.id);var venueControl=ids.length>1?`<label class="fieldLabel">Venue</label><select class="field" id="adminVenue" onchange="setAdminVenue(this.value)">${ids.map(function(id){var v=BARS.find(x=>x.id===id);return '<option value="'+esc(id)+'" '+(id===b.id?"selected":"")+'>'+esc(v?v.name:id)+'</option>'}).join("")}</select>`:`<div class="lockNote">Venue access: ${esc(b.name)} only</div>`;$("#statsPage").innerHTML=renderVenueControlsForBar({ids:ids,bar:b,levels:LEVELS,logo:logo,level:level,venueControl:venueControl});$("#adminCover").value=b.coverActive?b.cover:""}
function adminPatch(id,patch){return venueStaffController?venueStaffController.patch(id,patch):(canAdminVenue(id)?syncVenueAdminToSupabase(id,patch):showToast("That venue is locked"))}
function applyAdminFields(id){return venueStaffController?venueStaffController.applyFields(id):(function(){var b=BARS.find(x=>x.id===id),wait=parseInt($("#adminWait").value,10),cover=$("#adminCover").value,event=$("#adminEvent").value.trim();return adminPatch(id,{lvl:b.lvl,wait:isNaN(wait)?b.wait:Math.max(0,Math.min(180,wait)),coverActive:!!cover,cover:cover||b.cover,event:event||b.event})})()}
function bindMap(){var box=$("#mapBox"),canvas=$("#mapCanvas");if(!box||!canvas)return;function paint(){canvas.style.setProperty("--pan-x",mapPan.x+"px");canvas.style.setProperty("--pan-y",mapPan.y+"px")}paint();box.onpointerdown=function(e){mapPan.drag=true;mapPan.sx=e.clientX;mapPan.sy=e.clientY;mapPan.ox=mapPan.x;mapPan.oy=mapPan.y;box.setPointerCapture(e.pointerId)};box.onpointermove=function(e){if(!mapPan.drag)return;mapPan.x=Math.max(-110,Math.min(110,mapPan.ox+e.clientX-mapPan.sx));mapPan.y=Math.max(-110,Math.min(110,mapPan.oy+e.clientY-mapPan.sy));paint()};box.onpointerup=box.onpointercancel=function(){mapPan.drag=false}}
function initializeControllers(){
  barDetailController=createBarDetailController({findVenue:function(id){return BARS.find(b=>b.id===id)},setCurrentVenue:function(venue,tab){current=selectDetailVenue(appState,venue,tab);detailTab=appState.ui.detailTab},trackAppEvent:trackAppEvent,activePage:function(){return active},loadVenueReports:loadVenueReports,renderDetail:renderDetail,openDetailSheet:function(){var el=$("#detail");el.style.transform="";el.scrollTop=0;el.classList.add("open")},closeDetailSheet:function(){var el=$("#detail");el.style.transform="";el.classList.remove("open")},setDetailTab:function(tab){detailTab=selectDetailTab(appState,tab)},animateNavigate:navigateDetail});
  reportController=createReportController({currentVenue:function(){return current},trackAppEvent:trackAppEvent,setReportLevel:function(level){selectedReportLevel=selectReportLevel(appState,level)},openSheet:function(){$("#reportSheet").classList.add("open")},renderReportSheet:renderReportSheet,capturePresence:capturePresence,lineField:function(){return $("#lineField")},closeSheet:function(){$("#reportSheet").classList.remove("open")},submitReport:submitReport});
  ownerController=createOwnerController({isOwnerAccount:isOwnerAccount,showToast:showToast,ownerRequest:ownerRequest,renderOwnerDashboard:renderOwnerDashboard,clearOwnerData:function(){ownerData=null;appState.backend.ownerData=null},activePage:function(){return active},closeOwnerMap:function(){if(ownerMap){ownerMap.remove();ownerMap=null;appState.map.ownerMap=null}},setPage:setPage,publishVenue:function(){var id=$("#ownerVenue").value,b=BARS.find(v=>v.id===id),wait=parseInt($("#ownerWait").value,10),cover=$("#ownerCover").value,event=$("#ownerEvent").value.trim(),lvl=$("#ownerCrowd").value;if(!b)return;showToast("Publishing owner update...");return ownerAction("venue_live_update",{venue_id:id,crowd_level:lvl,wait_minutes:isNaN(wait)?0:wait,cover_amount:cover||null,cover_active:!!cover,event:event||null,note:"Owner control update"}).then(function(){return loadSupabaseStatus()}).then(function(){return ownerRequest()}).then(function(){renderOwnerDashboard();showToast("Owner update live")}).catch(function(err){showToast(err.message||"Owner update failed")})},setVenueStatus:function(status){var id=$("#ownerVenue").value,b=BARS.find(v=>v.id===id)||(ownerControlVenues().find(v=>v.id===id));if(!b)return;if(status==="hidden"&&!confirm("Hide "+b.name+" from public nightlife lists? You can reactivate it here later."))return;showToast("Updating venue status...");return ownerAction("set_venue_status",{venue_id:id,status:status,deprecated:false}).then(function(){return loadSupabaseStatus()}).then(function(){return ownerRequest()}).then(function(){renderOwnerDashboard();showToast(status==="active"?"Venue reactivated":"Venue hidden")}).catch(function(err){showToast(err.message||"Status update failed")})},setRedemption:function(id,status){showToast("Updating redemption...");return ownerAction("redemption_status",{redemption_id:id,status:status}).then(function(){return ownerRequest()}).then(function(){renderOwnerDashboard();showToast("Redemption updated")}).catch(function(err){showToast(err.message||"Redemption update failed")})},openVenue:function(id){var b=BARS.find(v=>v.id===id);$("#reportSheet").classList.add("open");$("#sheetcard").innerHTML='<span class="accessPill">OWNER DETAIL</span><h2>'+esc(b?b.name:"Venue")+'</h2><p class="sheetIntro">Loading recent signals, check-ins, reports, and audit history.</p>';return ownerAction("venue_detail",{venue_id:id}).then(renderOwnerVenueDetail).catch(function(err){$("#sheetcard").innerHTML='<span class="accessPill">OWNER DETAIL</span><h2>Could not load venue</h2><p class="sheetIntro">'+esc(err.message||"Owner detail failed")+'</p><button class="submit" onclick="closeSheet()">Close</button>'})}});
  venueStaffController=createVenueStaffController({setAdminVenue:function(id){adminVenueId=selectAdminVenue(appState,id)},renderAdminSheet:renderAdminSheet,canAdminVenue:canAdminVenue,showToast:showToast,syncVenueAdminToSupabase:syncVenueAdminToSupabase,refreshCurrentVenue:function(id){var b=BARS.find(x=>x.id===id);if(current&&current.id===id)current=b||current},renderDetailIfOpen:function(id){if(current&&current.id===id&&$("#detail").classList.contains("open"))renderDetail()},applyFields:function(id){var b=BARS.find(x=>x.id===id),wait=parseInt($("#adminWait").value,10),cover=$("#adminCover").value,event=$("#adminEvent").value.trim();return adminPatch(id,{lvl:b.lvl,wait:isNaN(wait)?b.wait:Math.max(0,Math.min(180,wait)),coverActive:!!cover,cover:cover||b.cover,event:event||b.event})}});
  mapController=createMapController({renderMap:function(){if(mapInstance){mapInstance.remove();mapInstance=null;appState.map.mapInstance=null}mapMarkers=[];appState.map.markers=mapMarkers;$("#mapPage").innerHTML=mapShellHtml();if(!MAPBOX_TOKEN){renderFallbackMap();$("#mapBox").insertAdjacentHTML("afterend",mapUnavailableHtml());return}loadMapbox().then(initRealMap).catch(function(){renderFallbackMap();showToast("Mapbox failed to load")})},loadMapbox:loadMapbox,initRealMap:initRealMap,renderFallbackMap:renderFallbackMap});
}
function renderAll(){renderRoleTabs();if(!authState)return renderAccountGate();if(accountNeedsSetup())return renderSetupGate();if(active==="statsPage"&&!canUseVenueControls())active=selectPage(appState,"livePage",canUseVenueControls);document.body.dataset.page=active;$all(".page").forEach(p=>p.classList.toggle("active",p.id===active));$all(".navbtn").forEach(n=>n.classList.toggle("on",n.dataset.page===active));if(active==="livePage")renderLive();if(active==="mapPage")renderMap();if(active==="highlightsPage")renderHighlightsPage();if(active==="statsPage"){if(isOwnerAccount())renderOwnerDashboard();else renderAdminSheet()}if(active==="profilePage")renderProfile()}
Object.assign(window,{$,esc,showToast,handleInstallPrimary,handleInstallSecondary,setPage,renderDetail,setDetailTab,toggleFav,openDetail,openMaps,checkInCurrent,openReport,renderReportSheet,setReportCrowd,setLinePreset,submitReport,closeSheet,openAdmin,setAdminVenue,renderAdminSheet,adminPatch,applyAdminFields,capturePresence,startAccountSession,submitEmailAuth,signOutAccount,setInteractionVisibility,saveDisplayName,handleAvatarFile,requestNotifications,requestSetupLocation,saveSetup,showLegalSheet,openProfileView,profileBack,redeemSkip,refreshOwnerDashboard,exitOwnerMode,ownerOpenVenue,ownerSetControlVenue,ownerPublishVenue,ownerSetVenueStatus,ownerSetRedemption,renderStats,trackAppEvent,closeDetail,setPulseVibe});
bindNavButtons();$("#tabU").onclick=function(){area=selectArea(appState,"main_gate",cacheState);renderLive()};$("#tabP").onclick=function(){area=selectArea(appState,"fourth_downtown",cacheState);renderLive()};
initializeControllers();
renderAll();setInterval(renderAll,60000);
setInterval(function(){if(authState&&(!document.visibilityState||document.visibilityState==="visible")){trackAppHeartbeat("heartbeat");maybeCapturePresence("foreground")}},60000);
setInterval(refreshOwnerDashboardSilent,15000);
initSupabase();
(function(){
  var el=document.getElementById("detail"),g={sx:0,sy:0,t0:0,dir:null,active:false};
  el.addEventListener("touchstart",function(e){
    if(e.touches.length!==1)return;
    g.sx=e.touches[0].clientX;g.sy=e.touches[0].clientY;g.t0=e.timeStamp;g.dir=null;g.active=true;
  },{passive:true});
  el.addEventListener("touchmove",function(e){
    if(!g.active||e.touches.length!==1)return;
    var dx=e.touches[0].clientX-g.sx,dy=e.touches[0].clientY-g.sy;
    if(!g.dir&&(Math.abs(dx)>9||Math.abs(dy)>9))g.dir=Math.abs(dx)>Math.abs(dy)?"h":"v";
    if(g.dir==="v"&&dy>0&&el.scrollTop<=0)e.preventDefault();
  },{passive:false});
  el.addEventListener("touchend",function(e){
    if(!g.active)return;g.active=false;
    var dx=e.changedTouches[0].clientX-g.sx,dy=e.changedTouches[0].clientY-g.sy,dt=Math.max(1,e.timeStamp-g.t0);
    var vx=dx/dt,vy=dy/dt;
    if(g.dir==="v"&&(dy>window.innerHeight*0.22||vy>0.45)){closeDetail();return;}
    if(g.dir==="h"){
      var bars=barsInArea(),idx=bars.findIndex(function(b){return b.id===current.id;});
      if((dx<-55||vx<-0.4)&&idx<bars.length-1)navigateDetail(bars[idx+1].id,"left");
      else if((dx>55||vx>0.4)&&idx>0)navigateDetail(bars[idx-1].id,"right");
    }
  },{passive:true});
})();
(function(){var s=document.getElementById("splash");setTimeout(function(){s.classList.add("out");setTimeout(function(){s.style.display="none";setTimeout(function(){installPrompt.maybeShowAfterSplash();},800);},400);},3200)})();
if("serviceWorker" in navigator){window.addEventListener("load",function(){navigator.serviceWorker.register("/sw.js").then(function(reg){reg.update&&reg.update()}).catch(function(){})})}
