-- LineUp auth hardening: staff codes must not be stored or queried as plaintext.
-- Existing legacy plaintext codes should be rotated through owner-actions after this migration.

alter table if exists public.venue_staff_codes
  add column if not exists code_hash text,
  add column if not exists code_last4 text,
  add column if not exists created_by_user_id uuid references auth.users(id) on delete set null,
  add column if not exists rotated_from_id uuid references public.venue_staff_codes(id) on delete set null;

create unique index if not exists venue_staff_codes_active_hash_idx
  on public.venue_staff_codes (venue_id, code_hash)
  where active = true and code_hash is not null;

create index if not exists venue_staff_codes_lookup_idx
  on public.venue_staff_codes (venue_id, active, expires_at);

comment on column public.venue_staff_codes.code_hash is
  'SHA-256 hash generated by Edge Functions from LINEUP_STAFF_CODE_PEPPER, venue_id, and the submitted code.';

comment on column public.venue_staff_codes.code_last4 is
  'Non-secret display preview only. Never use this for authentication.';

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'venue_staff_codes'
      and column_name = 'code'
  ) then
    update public.venue_staff_codes set code = null where code is not null;

    if not exists (
      select 1
      from pg_constraint
      where conname = 'venue_staff_codes_no_plaintext_code'
    ) then
      alter table public.venue_staff_codes
        add constraint venue_staff_codes_no_plaintext_code
        check (code is null);
    end if;
  end if;
end $$;
